version: '3.4'

services:
  djangoapimedic:
    image: djangoapimedic
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysqldb
    links:
      - mysqldb

    env_file: /.env
    ports:
      - $DJANGO_LOCAL_PORT:$DJANGO_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT

    mysqldb:
      image: mysql
      env_file: /.env
      environment:
        - MYSQL_USER=$MYSQLDB_USER
        - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT