# Generated by Django 5.0.6 on 2024-08-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=1, unique=True, verbose_name='Símbolo')),
            ],
        ),
    ]
