# Generated by Django 5.0.6 on 2024-05-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Código del Medicamento'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.CharField(max_length=100, verbose_name='Unidad de Medida'),
        ),
    ]
