# Generated by Django 5.0.6 on 2024-06-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_alter_medication_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Compuesto químico'),
        ),
    ]
