# Generated by Django 5.0.6 on 2024-06-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_alter_medication_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('symbol', models.CharField(max_length=10, verbose_name='Símbolo')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='presentation',
            field=models.CharField(default='tabletas', max_length=100, verbose_name='Presentación'),
            preserve_default=False,
        ),
    ]
