# Generated by Django 5.0.6 on 2024-06-01 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_currency_medication_presentation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
