# Generated by Django 5.0.6 on 2024-06-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_delete_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='medications', to='medications.category', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
