# Generated by Django 5.0.6 on 2024-06-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_alter_medication_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='medication',
            name='categories',
            field=models.ManyToManyField(related_name='medications', to='medications.category', verbose_name='Categorías'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='stock',
            field=models.CharField(max_length=255, verbose_name='Inventario'),
        ),
    ]
