# Generated by Django 5.0.6 on 2024-07-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0008_alter_medication_options_alter_medication_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='indications',
            field=models.TextField(blank=True, default='Las que indique el médico', null=True, verbose_name='Indicaciones'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='recommended_dosage',
            field=models.CharField(blank=True, default='La que indique el médico', max_length=255, null=True, verbose_name='Dosis Recomendada'),
        ),
    ]
