# Generated by Django 5.0.6 on 2024-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_alter_medication_indications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['name'],
            },
        ),
    ]
