# Generated by Django 5.0.6 on 2024-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0013_rename_manufacturer_medicationsmanufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationsChemicalCompound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Compuesto Químico',
                'verbose_name_plural': 'Compuestos Químicos',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='medication',
            name='code',
        ),
        migrations.AddField(
            model_name='medication',
            name='chemical_compound',
            field=models.ManyToManyField(to='medications.medicationschemicalcompound', verbose_name='Compuesto Químico'),
        ),
    ]
