# Generated by Django 5.0.6 on 2024-08-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0014_medicationschemicalcompound_remove_medication_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschemicalcompound',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
