# Generated by Django 5.0.6 on 2024-08-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0015_medicationschemicalcompound_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.RemoveField(
            model_name='medication',
            name='contraindications',
        ),
        migrations.AddField(
            model_name='medication',
            name='contraindications',
            field=models.ManyToManyField(to='medications.medicationcontraindication', verbose_name='Contraindicaciones'),
        ),
    ]
