# Generated by Django 5.0.6 on 2024-08-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0017_rename_medicationcontraindication_medicationcontraindications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicationContraindications',
            new_name='MedicationsContraindications',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='presentation',
        ),
        migrations.AlterField(
            model_name='medicationspresentation',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='medication',
            name='presentation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='medications.medicationspresentation', verbose_name='Presentación'),
            preserve_default=False,
        ),
    ]
