# Generated by Django 5.0.6 on 2024-08-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0018_rename_medicationcontraindications_medicationscontraindications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationspresentation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
