# Generated by Django 5.0.6 on 2024-08-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0020_medicationsunitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medications.medicationsunitofmeasure', verbose_name='Unidad de Medida'),
        ),
    ]
