# Generated by Django 5.0.6 on 2024-08-12 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('medications', '0021_alter_medication_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.currency', verbose_name='Moneda'),
        ),
    ]
