# Generated by Django 5.0.6 on 2024-06-16 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del paciente')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido del paciente')),
                ('age', models.SmallIntegerField(verbose_name='Edad del paciente')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento del paciente')),
                ('dpi', models.CharField(blank=True, max_length=13, null=True, verbose_name='DPI del paciente')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Género del paciente')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección del paciente')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del paciente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico del paciente')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Grupo sanguíneo del paciente')),
                ('history', models.TextField(blank=True, max_length=500, null=True, verbose_name='Historia del paciente')),
                ('civil_status', models.CharField(choices=[('Soltero', 'Soltera'), ('Casado', 'Casada'), ('Divorciado', 'Divorciada'), ('Viudo', 'Viuda')], max_length=25, verbose_name='Estado civíl')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
                ('bring_medical_prescription', models.BooleanField(default=False, verbose_name='Trae Receta Médica')),
                ('is_alergic', models.BooleanField(default=False, verbose_name='Es Alergico')),
                ('is_alergic_to', models.TextField(blank=True, null=True, verbose_name='Es Alergico a')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura')),
                ('ocupation', models.ManyToManyField(related_name='patients', to='patient.ocupation', verbose_name='Ocupación')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['id'],
            },
        ),
    ]
