# Generated by Django 5.0.6 on 2024-06-17 18:00

import patient.validators.dpi_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='dpi',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[patient.validators.dpi_validation.dpi_is_valid], verbose_name='DPI del paciente'),
        ),
    ]
