# Generated by Django 5.0.6 on 2024-06-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alergy_alter_patient_dpi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alergy',
            options={'ordering': ['name'], 'verbose_name': 'Alergía', 'verbose_name_plural': 'Alergias'},
        ),
        migrations.AlterModelOptions(
            name='ocupation',
            options={'ordering': ['name'], 'verbose_name': 'Ocupación', 'verbose_name_plural': 'Ocupaciones'},
        ),
    ]
